import { useState } from "react";
import CareerAnalyzer from "./components/CareerAnalyzer";

function App() {
  const [showAnalyzer, setShowAnalyzer] = useState(false);

  if (showAnalyzer) {
    return (
      <div className="app">

        <header className="navbar">

          <div className="logo">
            🚀 CareerPilot
          </div>

          <button
            className="back-button"
            onClick={() => setShowAnalyzer(false)}
          >
            ← Back Home
          </button>

        </header>

        <CareerAnalyzer />

      </div>
    );
  }

  return (
    <div className="app">

      <header className="navbar">

        <div className="logo">
          🚀 CareerPilot
        </div>

        <nav>
          <a href="#home">Home</a>
          <a href="#features">Features</a>
          <a href="#about">About</a>
        </nav>
      </header>


      <main>

        <section className="hero" id="home">

          <div className="hero-content">

            <p className="badge">
              AI-POWERED CAREER ASSISTANT
            </p>

            <h1>
              Build Your Career
              <span> With AI.</span>
            </h1>

            <p className="hero-description">

              Analyze your resume, understand job requirements,
              discover skill gaps, and prepare for interviews
              with your personal AI CareerPilot.

            </p>

            <button
              className="primary-button"
              onClick={() => setShowAnalyzer(true)}
            >
              🚀 Analyze My Career
            </button>

          </div>

        </section>


        <section className="features" id="features">

          <h2>
            Everything You Need to Grow
          </h2>

          <div className="feature-grid">

            <div className="feature-card">

              <div className="icon">📄</div>

              <h3>
                Resume Analyzer
              </h3>

              <p>
                Analyze your resume and identify strengths,
                weaknesses, and improvement opportunities.
              </p>

            </div>


            <div className="feature-card">

              <div className="icon">💼</div>

              <h3>
                Job Analyzer
              </h3>

              <p>
                Compare your resume with a target job description
                and discover important skill gaps.
              </p>

            </div>


            <div className="feature-card">

              <div className="icon">🎤</div>

              <h3>
                Interview Coach
              </h3>

              <p>
                Practice personalized technical and behavioral
                interview questions generated by AI.
              </p>

            </div>


            <div className="feature-card">

              <div className="icon">🗺️</div>

              <h3>
                Career Roadmap
              </h3>

              <p>
                Get a personalized learning roadmap based on
                your career goals and missing skills.
              </p>

            </div>

          </div>

        </section>

      </main>


      <footer id="about">

        <p>
          © 2026 AI CareerPilot • Built with React & AI
        </p>

      </footer>

    </div>
  );
}

export default App;